AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  bpipe-vpc-endpoint-discover

  Sample SAM Template for bpipe-vpc-endpoint-discover

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 360

Resources:
  BPipeEndPointDiscoverFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: bpipe_endpt_discover/
      Handler: handler.lambda_handler
      Runtime: python3.8
      MemorySize: 512
      Events:
        Probe:
          Type: CloudWatchEvent # More info about CloudWatchEvent Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cloudwatchevent
          Properties:
            Pattern:
              source:
                - aws.ec2
              detail-type:
                - EC2 Instance State-change Notification
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SQS_URL: "https://sqs.us-east-1.amazonaws.com/191791126208/csa-healthcheck-bpipe-endpoint"
          SNS_ARN: "arn:aws:sns:us-east-1:192592784707:bpipe-publish-endpoint-to-canary"
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - Statement:
            - Sid: describeVPCEndpoints
              Effect: Allow
              Action:
                - "ec2:DescribeVpcEndpoints"
              Resource: "*"
        - Statement:
            - Sid: pushHealthCheckRequest
              Effect: Allow
              Action:
                - "SNS:Publish"
              Resource: "arn:aws:sns:*:*:bpipe*"
        - Statement:
            - Sid: sendSQSMessage
              Effect: Allow
              Action:
                - "sqs:SendMessage"
              Resource: "arn:aws:sqs:*:*:bpipe*"

Outputs:
  BPipeEndPointDiscoverFunction:
    Description: "Discover endpoint Lambda Function ARN"
    Value: !GetAtt BPipeEndPointDiscoverFunction.Arn
  BPipeEndPointDiscoverFunctionIamRole:
    Description: "Implicit IAM Role created for Discover endpoint function"
    Value: !GetAtt BPipeEndPointDiscoverFunctionRole.Arn
